spring:
  profiles:
    active: test
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
#    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/e_commerce?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_SMTP_USERNAME}
    password: ${SPRING_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  application:
    name: "VendiVerse"
  data:
    redis:
      port: 6379
      host: localhost
  config:
    import: optional:file:.env[.properties]

jwt:
  issuer: ${JWT_ISSUER}
  secret-key: ${JWT_SECRET_KEY}