spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: venver_user
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_SMTP_USERNAME}
    password: ${SPRING_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  data:
    redis:
      port: 6379
      host: localhost

logging:
  level:
    org:
      hibernate:
        SQL: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        mail: DEBUG
        security: TRACE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
jwt:
  issuer: ${JWT_ISSUER}
  secret-key: ${JWT_SECRET_KEY}
server:
  port: 8080