spring:
  application:
    name: venver-product
  data:
    redis:
      port: 6379
      host: localhost
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: 8081